# This program computes and outputs the Bonferroni-p outliers of a time series generated by a linear model of flux 
# against a 2nd degree polynomial of time. The input format is a two column .csv (time, flux) and may include 
# restrictions on the indices to use to account for jumps in flux.

# The output is placed in a .csv file with two columns (outlier_time, outlier_bonferroniP)

args = commandArgs(trailingOnly=TRUE)
file_in = args[1]
first_index = args[2]
last_index = args[3]
file_out = args[4]


data = read.csv(file_in, header=FALSE)
time = data$V1[first_index:last_index]
flux = data$V2[first_index:last_index]
time_squared = time * time

model = lm(flux ~ time + time_squared)

sink(file_out)
oTest = car::outlierTest(model, label=time)


for(i in 1:length(oTest$bonf.p)) {
	myName = names(oTest$bonf.p[i])
	myValue = unname(oTest$bonf.p[i])
	cat(myName, ",", myValue, "\n", sep="", labels="")
}
